Question 3 (b)

In [2]:
import pprint
import scipy
import scipy.linalg
import math
import numpy as np

In [3]:
A = np.array([[1, 2, 3], [-1, 2, 1], [0, 1, 1]])  
Q, R = scipy.linalg.qr(A)

In [4]:
print( "A:")
print(A)

print ("Q:")
print(Q)

print ("R:")
print(R)

A:
[[ 1  2  3]
 [-1  2  1]
 [ 0  1  1]]
Q:
[[-0.70710678 -0.66666667 -0.23570226]
 [ 0.70710678 -0.66666667 -0.23570226]
 [-0.         -0.33333333  0.94280904]]
R:
[[-1.41421356e+00  6.66133815e-16 -1.41421356e+00]
 [ 0.00000000e+00 -3.00000000e+00 -3.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.14863726e-16]]


Question 4

In [8]:
def matrix_conv(A):
    A_i = A                             #initialize A_i to be the input matrix A
    for i in range(500):                #iterate 500 times
        Q_i, R_i = scipy.linalg.qr(A_i) #QR decomposition to get Q, R matrix
        A_i = np.dot(R_i, Q_i)          #R * Q to get the new A_i
     
    A_j = A                             #same process but iterate 5000 times
    for j in range(4999):
        Q_j, R_j = scipy.linalg.qr(A_j)
        A_j = np.dot(R_j, Q_j)
    print(A_i)
    print(A_j)

In [9]:
B = np.array([[-9, 8, 3, 4], [8, 7, -6, 5], [3, -6, 1, -2], [4, 5, -2, 10]])   # 4*4 symmetric matrix with real eigenvalues

[[-9  8  3  4]
 [ 8  7 -6  5]
 [ 3 -6  1 -2]
 [ 4  5 -2 10]]


In [10]:
matrix_conv(B)   # The matrix converges to a diagonal matrix as the iteration rounds increase

[[ 1.75711389e+001  2.03065361e-014 -3.85843251e-015  9.28506206e-016]
 [ 9.21977041e-044 -1.42794741e+001 -7.60375278e-016 -1.39699037e-015]
 [-3.81273605e-268  7.87718475e-224  5.09683914e+000 -1.10594660e-015]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  6.11496112e-001]]
[[ 1.75711389e+001  2.03065361e-014  3.85843251e-015 -9.28506206e-016]
 [-2.81617418e-322 -1.42794741e+001  7.60375278e-016  1.39699037e-015]
 [ 0.00000000e+000  0.00000000e+000  5.09683914e+000 -1.10594660e-015]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  6.11496112e-001]]


In [11]:
C = np.array([[1, 2, 3],[2, 1, 4], [3, 4, 2]])    # 3*3 symmetric matrix with real eigenvalues

In [12]:
matrix_conv(C)     # The matrix converges to a diagonal matrix as the iteration rounds increase 

[[ 7.50147445e+000  6.11130172e-016 -2.07567916e-015]
 [-1.89441043e-226 -2.64452674e+000 -2.18791791e-016]
 [ 0.00000000e+000  1.33759916e-244 -8.56947714e-001]]
[[ 7.50147445e+00  6.11130172e-16  2.07567916e-15]
 [ 0.00000000e+00 -2.64452674e+00  2.18791791e-16]
 [ 0.00000000e+00  0.00000000e+00 -8.56947714e-01]]


In [14]:
D = np.array([[2, 0, 0], [0, 2, 3], [0, -3, 2]])   # 3*3 matrix with complex eigenvalues

In [15]:
matrix_conv(D)    # The matrix does not converge at all! The outcome is still the same as the original matrix

[[ 2.  0.  0.]
 [ 0.  2.  3.]
 [ 0. -3.  2.]]
[[ 2.  0.  0.]
 [ 0.  2. -3.]
 [ 0.  3.  2.]]


In [17]:
E = np.array([[-1, 0, 0, 0], [0, 2, 0, 0], [0, 0, -4, 2], [0, 0, -2, -4]])  # 4*4 matrix with complex eigenvalues

In [18]:
matrix_conv(E)   # The matrix does not converge at all! The outcome is still the same as the original matrix

[[-1.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0. -4.  2.]
 [ 0.  0. -2. -4.]]
[[-1.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0. -4. -2.]
 [ 0.  0.  2. -4.]]
